categories_layout:
  default: categories_and_latest_topics
  type: enum
  choices:
    - categories_only
    - categories_with_featured_topics
    - categories_and_top_topics
    - categories_boxes
    - categories_boxes_with_topics